import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import { ThemeProvider } from "../components/Mat_tail_export";
import "./globals.css";
import { SidebarWithContentSeparator } from "../components/sidebar";
import { NavbarDark } from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>
          <div className="m-4">
            <NavbarDark />
          </div>
            <div className="flex flex-row gap-10 mt-0">
            <SidebarWithContentSeparator />
              <div className="mt-8">
                {children}
              </div>
            </div>
        </body>
      </ThemeProvider>
    </html>
  );
}
